### ISSUE TITLE
Incorrect pip install reference

### ISSUE THREAD

**Issue by gmkbenjamin** [govau/notify-client-python#4]
Hello team,
In the README file 'pip install notifications-python-client' doesn't seem to be correct.

It appears the notifications-python-client module (https://pypi.org/project/notifications-python-client/) is for GOV.UK Notify.

**Comment by jonathaningram** [comment]
Hi @gmkbenjamin thanks for the issue report! You're right—we're on it.

**Comment by andrewoh531** [comment]
This issue should be fixed by: https://github.com/govau/notify-client-python/pull/5
